services:
  qdrant:
    image: qdrant/qdrant
    profiles:
      - qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrantdata:/qdrant/storage
    networks:
      - azen_network
    restart: unless-stopped

volumes:
  qdrantdata:
